version: '3.2'
services:
  provider1:
      build: ./frontend
      tty: true
      volumes:
        - './frontend/source/dist/sampleapp:/frontend-dir-inside-container'
  provider2:
      build: ./frontend
      tty: true
      volumes:
        - './frontend/source/dist/sampleapp:/frontend-dir-inside-container'
  provider3:
      build: ./frontend
      tty: true
      volumes:
        - './frontend/source/dist/sampleapp:/frontend-dir-inside-container'
  loadbalancer:
      build: ./load-balancer
      tty: true
      links:
          - provider1
          - provider2
          - provider3
      ports:
          - '8080:8081'
volumes:
  frontend: