version: '3.5'
services:
  web:
    image: deedonny/samplewebapp1:0.0.1
    logging:
      driver: "json-file"
      options:
          max-file: 5
          max-size: 10m
    tty: true
    ports:
      - '4200:4200'
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure